[package]
name = "libwallet"
version = "0.1.0"
authors = ["Daniel Olano <me@olanod.com>"]
edition = "2018"

[dependencies]
hashbrown = "0.7.2"
tiny-bip39 = "0.7.3"
jsonrpsee = { git = "https://github.com/paritytech/jsonrpsee.git", optional = true }

[dev-dependencies]
async-std = { version = "1.5.0", features = ["attributes"] }

[features]
std = []
chain = ["std", "jsonrpsee"]


[[example]]
name = "balance"
required-features = ["chain"]
