[package]
name = "scales"
description = "SCALE Serialization"
version = "0.2.0"
authors = ["Daniel Olano <daniel@olanod.com>"]
edition = "2018"
repository = "https://github.com/valibre-org/scales"

[dependencies]
byteorder = { version = "1.4.3", default-features = false }
codec = { version = "2.2.0", package = "parity-scale-codec", default-features = false, optional = true }
core2 = { version = "0.3.1", default-features = false, optional = true }
scale-info = { version = "0.10.0", default-features = false }
serde = { version = "1.0.126", default-features = false }

[features]
default = ["std", "serializer"]
std = ["scale-info/std", "core2/std"]
serializer = ["core2", "codec"]

[dev-dependencies]
anyhow = "1.0.42"
codec = { version = "2.2.0", package = "parity-scale-codec", features = ["derive"] }
scale-info = { version = "0.10.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.126", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.66", default-features = false, features = ["alloc"] }
