[package]
name = "scales"
version = "0.1.0"
authors = ["Daniel Olano <daniel@olanod.com>"]
edition = "2018"

[dependencies]
scale-info = { version = "0.6.0", default-features = false }
serde = { version = "1.0.126", default-features = false }

[dev-dependencies]
parity-scale-codec = { version = "2.1.3", features = ["derive"] }
scale-info = { version = "0.6.0", features = ["derive"] }
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
