[package]
name = "scales"
description = "SCALE Serialization"
version = "0.2.0"
authors = ["Daniel Olano <daniel@olanod.com>"]
edition = "2018"
repository = "https://github.com/valibre-org/scales"

[dependencies]
byteorder = { version = "1.4.3", default-features = false }
scale-info = { version = "0.10.0", default-features = false }
serde = { version = "1.0.126", default-features = false }

[features]
std = ["scale-info/std"]

[dev-dependencies]
anyhow = "1.0.42"
parity-scale-codec = { version = "2.2.0", features = ["derive"] }
scale-info = { version = "0.10.0", features = ["derive"] }
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.66"
