[package]
name = "libwallet"
version = "0.1.0"
authors = ["Daniel Olano <me@olanod.com>"]
edition = "2018"

[dependencies]
tiny-bip39 = "0.8.0"
async-trait = "0.1.42"
thiserror = "1.0.24"
sp-core = "3.0.0"

[dev-dependencies]
async-std = { version = "1.9.0", features = ["attributes"] }

[features]
std = []
