[package]
name = "sube"
description = "SUBmit Extrinsics to a Substrate node"
license = "Apache-2.0"
version = "0.2.0"
authors = ["Daniel Olano <daniel@olanod.com>"]
edition = "2018"
repository = "https://github.com/valibre-org/sube"

[dependencies]
async-trait = "0.1.51"
blake2 = { version = "0.9.1", default-features = false }
byteorder = "1.4.3"
frame-metadata = { git = "https://github.com/paritytech/frame-metadata.git", branch = "main", default-features = false, features = ["std"] }
scale-info = { version = "0.10.0", optional = true }
futures-lite = "1.12.0"
hex = "0.4.3"
jsonrpc = "0.12.0"
log = "0.4.14"
once_cell = "1.8.0"
codec = { version = "2.2.0", package = "parity-scale-codec" }
twox-hash = { version = "1.6.0", default-features = false }
surf = { version = "2.2.0", default_features = false, optional = true }

anyhow = { version = "1.0.42", optional = true }
async-std = { version = "1.9.0", default_features = false, optional = true }
serde_json = { version = "1.0.66", default-features = false, optional = true }
stderrlog = { version = "0.5.1", optional = true }
structopt = { version = "0.3.22", optional = true }
url = { version = "2.2.2", optional = true }

async-tungstenite = { version = "0.14.0", features = ["async-std-runtime"], optional = true }
futures-channel = { version = "0.3.16", default-features = false, features = ["alloc"] }
futures-util = { version = "0.3.16", default-features = false, features = ["sink"] }
async-mutex = "1.4.0"
cfg-if = "1.0.0"
async-tls = { version = "0.11.0", default-features = false, optional = true }

[dev-dependencies]
async-std = { version = "1.9.0", features = ["attributes"] }

[features]
# default = ["http", "wss", "v14"]
bin = [
	"anyhow",
	"async-std/attributes",
	"http",
	"serde_json",
	"stderrlog",
	"structopt",
	"url",
	"wss",
]
http = ["surf/h1-client-rustls"]
ws = ["async-std", "async-tungstenite"]
wss = ["ws", "async-tls", "async-tungstenite/async-tls"]
v12 = ["frame-metadata/v12"]
v13 = ["frame-metadata/v13"]
v14 = ["frame-metadata/v14", "scale-info"]

[[bin]]
name = "sube"
required-features = ["bin"]
